substitutions:
  preset_slug: "e"

esphome:
  project:
    name: gaetanars.frangipool_electrolyser
    version: dev

dashboard_import:
  package_import_url: github://gaetanars/FrangiPool/frangipool-e.yaml@main

packages:
  base: !include packages/base.yaml
  filtration: !include packages/filtration.yaml
  electrolyser: !include packages/electrolyser.yaml
