substitutions:
  local_temp_address: "0x0000000000000000"  # Remplacer par l'adresse de votre sonde locale (voir logs ESPHome au démarrage)
  temp_address: "0x0000000000000000"  # Remplacer par l'adresse de votre sonde canalisation
  preset_slug: "be"

esphome:
  project:
    name: frangipool.be
    version: "0.2.0"

dashboard_import:
  package_import_url: github://gaetanars/FrangiPool/frangipool-be.yaml@main

packages:
  base: github://gaetanars/FrangiPool/packages/base.yaml@main
  filtration: github://gaetanars/FrangiPool/packages/filtration.yaml@main
  electrolyser: github://gaetanars/FrangiPool/packages/electrolyser.yaml@main
  booster: github://gaetanars/FrangiPool/packages/booster.yaml@main
