substitutions:
  preset_slug: "ber"

esphome:
  project:
    name: frangipool.ber
    version: "0.2.0"

dashboard_import:
  package_import_url: github://gaetanars/FrangiPool/frangipool-ber.yaml@main

packages:
  base: !include packages/base.yaml
  filtration: !include packages/filtration.yaml
  i2c_ads1115: !include packages/i2c_ads1115.yaml
  electrolyser: !include packages/electrolyser.yaml
  booster: !include packages/booster.yaml
  redox: !include packages/redox.yaml
  redox_electrolyser: !include packages/redox_electrolyser.yaml
