substitutions:
  preset_slug: "bep"

esphome:
  project:
    name: frangipool.bep
    version: "0.2.0"

dashboard_import:
  package_import_url: github://gaetanars/FrangiPool/frangipool-bep.yaml@main

packages:
  base: !include packages/base.yaml
  filtration: !include packages/filtration.yaml
  i2c_ads1115: !include packages/i2c_ads1115.yaml
  electrolyser: !include packages/electrolyser.yaml
  booster: !include packages/booster.yaml
  ph: !include packages/ph.yaml
