substitutions:
  preset_slug: "be"

esphome:
  project:
    name: frangipool.be
    version: "0.2.0"

dashboard_import:
  package_import_url: github://gaetanars/FrangiPool/frangipool-be.yaml@main

packages:
  base: !include packages/base.yaml
  filtration: !include packages/filtration.yaml
  electrolyser: !include packages/electrolyser.yaml
  booster: !include packages/booster.yaml
