substitutions:
  name: frangipool
  friendly_name: FrangiPool
  local_temp_address: "0x0000000000000000"  # Remplacer par l'adresse de votre sonde locale (voir logs ESPHome au démarrage)
  temp_address: "0x0000000000000000"  # Remplacer par l'adresse de votre sonde canalisation

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: frangipool.salt_booster_full
    version: "2.0.0"

dashboard_import:
  package_import_url: github://gaetanars/FrangiPool/salt_booster_full.yaml@main

packages:
  base: github://gaetanars/FrangiPool/packages/base.yaml@main
  filtration: github://gaetanars/FrangiPool/packages/filtration.yaml@main
  i2c_ads1115: github://gaetanars/FrangiPool/packages/i2c_ads1115.yaml@main
  electrolyser: github://gaetanars/FrangiPool/packages/electrolyser.yaml@main
  booster: github://gaetanars/FrangiPool/packages/booster.yaml@main
  redox: github://gaetanars/FrangiPool/packages/redox.yaml@main
  ph: github://gaetanars/FrangiPool/packages/ph.yaml@main
  redox_electrolyser: github://gaetanars/FrangiPool/packages/redox_electrolyser.yaml@main
