globals:
  - id: g_electrolyser_active_minutes
    type: int
    restore_value: True
    initial_value: '0'

switch:
  - platform: gpio
    pin:
      number: GPIO27
      inverted: false
    name: Electrolyseur
    id: electrolyser
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:chemical-weapon
    on_turn_off:
      then:
        - globals.set:
            id: g_electrolyser_active_minutes
            value: '0'

sensor:
  - platform: template
    name: Durée Electrolyse
    id: electrolyser_duration
    unit_of_measurement: min
    device_class: duration
    state_class: total_increasing
    accuracy_decimals: 0
    icon: mdi:chemical-weapon
    update_interval: 60s
    lambda: |-
      return (float) id(g_electrolyser_active_minutes);

interval:
  - interval: 60s
    then:
      - if:
          condition:
            and:
              - switch.is_on: pump
              - switch.is_on: electrolyser
          then:
            - lambda: "id(g_electrolyser_active_minutes) += 1;"
