globals:
  - id: g_store_pool_ph
    type: float
    restore_value: True
  - id: g_ph_offset
    type: float
    restore_value: True

sensor:
  - platform: ads1115
    id: ads1115_a1
    internal: true
    multiplexer: 'A1_GND'
    gain: 6.144
    update_interval: 10s

  - platform: template
    name: pH Temps Réel
    state_class: "measurement"
    icon: mdi:ph
    entity_category: diagnostic
    id: realtime_ph
    accuracy_decimals: 1
    update_interval: 10s
    lambda: return 3.56 * id(ads1115_a1).state - 1.889 + id(g_ph_offset);
    filters:
      - sliding_window_moving_average:
          window_size: 18
          send_every: 6
          send_first_at: 6

  - platform: template
    name: pH
    state_class: "measurement"
    icon: mdi:ph
    id: pool_ph
    accuracy_decimals: 1
    lambda: return id(g_store_pool_ph);

  - platform: template
    name: pH Offset
    entity_category: diagnostic
    id: ph_offset_sensor
    lambda: return id(g_ph_offset);

button:
  - platform: template
    name: pH Calibration 7.00
    entity_category: config
    on_press:
      then:
        - globals.set:
            id: g_ph_offset
            value: !lambda "return 7.0 - 3.56 * id(ads1115_a1).state + 1.889;"
        - component.update: ph_offset_sensor
        - component.update: realtime_ph

interval:
  - interval: 1min
    then:
      - if:
          condition:
            and:
              - switch.is_on: pump
              - lambda: |-
                  if (id(pump_uptime).state >= id(pump_uptime_delay).state){
                    return true;
                  } else {
                    return false;
                  }
          then:
            - globals.set:
                id: g_store_pool_ph
                value: !lambda "return id(realtime_ph).state;"
