globals:
  - id: store_pool_redox
    type: float
    restore_value: true
  - id: redox_offset
    type: float
    restore_value: true
  - id: last_redox_trend_value
    type: float
    restore_value: true
    initial_value: '0.0'
  - id: redox_trend_state
    type: int
    restore_value: no
    initial_value: '0'

number:
  - platform: template
    entity_category: config
    name: "Redox Calibration Manuelle"
    min_value: -300
    max_value: 300
    step: 1
    optimistic: true
    initial_value: 0
    restore_value: true
    id: "redox_manual_offset"

sensor:
  - platform: ads1115
    name: "ADS1115 Channel A0-GND"
    id: ads1115_a0
    unit_of_measurement: "mV"
    device_class: "voltage"
    state_class: "measurement"
    entity_category: diagnostic
    multiplexer: 'A0_GND'
    gain: 6.144
    update_interval: 10s
    filters:
      - multiply: 1000

  - platform: template
    name: Redox Temps Réel
    unit_of_measurement: "mV"
    device_class: "voltage"
    state_class: "measurement"
    icon: mdi:chemical-weapon
    entity_category: diagnostic
    id: realtime_redox
    accuracy_decimals: 0
    update_interval: 10s
    lambda: |
      if (id(redox_manual_offset).state != 0.0) return ((2500-id(ads1115_a0).state)/1.037) + id(redox_manual_offset).state;
      else return ((2500-id(ads1115_a0).state)/1.037) + id(redox_offset);
    filters:
      - sliding_window_moving_average:
          window_size: 12
          send_every: 3

  - platform: template
    name: Redox
    unit_of_measurement: "mV"
    device_class: "voltage"
    state_class: "measurement"
    icon: mdi:chemical-weapon
    id: pool_redox
    accuracy_decimals: 0
    lambda: return id(store_pool_redox);

  - platform: template
    name: Redox Offset
    entity_category: diagnostic
    id: redox_offset_sensor
    lambda: return id(redox_offset);

text_sensor:
  - platform: template
    name: "Tendance Redox"
    entity_category: diagnostic
    lambda: |-
      if (id(redox_trend_state) == 1) {
        return {"En montée"};
      } else if (id(redox_trend_state) == -1) {
        return {"En descente"};
      } else {
        return {"Stable"};
      }

button:
  - platform: template
    name: Redox Calibration 225mV
    entity_category: config
    on_press:
      then:
        - number.set:
            id: redox_manual_offset
            value: 0
        - delay: 180s
        - globals.set:
            id: redox_offset
            value: !lambda "return 225 - (((2500-id(ads1115_a0).state)/1.037));"
        - component.update: redox_offset_sensor
        - component.update: realtime_redox
        - homeassistant.action:
            action: persistent_notification.create
            data:
              title: Message from ${friendly_name}
            data_template:
              message: Calibration Redox à 225mV terminée !

  - platform: template
    name: Redox Calibration 475mV
    entity_category: config
    on_press:
      then:
        - number.set:
            id: redox_manual_offset
            value: 0
        - delay: 180s
        - globals.set:
            id: redox_offset
            value: !lambda "return 475 - (((2500-id(ads1115_a0).state)/1.037));"
        - component.update: redox_offset_sensor
        - component.update: realtime_redox
        - homeassistant.action:
            action: persistent_notification.create
            data:
              title: Message from ${friendly_name}
            data_template:
              message: Calibration Redox à 475mV terminée !

  - platform: template
    name: Redox Calibration Reset
    entity_category: config
    on_press:
      then:
        - globals.set:
            id: redox_offset
            value: '0.0'
        - component.update: redox_offset_sensor
        - component.update: realtime_redox

interval:
  - interval: 1min
    then:
      - if:
          condition:
            and:
              - switch.is_on: pump
              - lambda: |-
                  if (id(pump_uptime).state >= id(pump_uptime_delay).state){
                    return true;
                  } else {
                    return false;
                  }
          then:
            - globals.set:
                id: store_pool_redox
                value: !lambda "return id(realtime_redox).state;"
            - component.update: pool_redox

  - interval: 5min
    then:
      - lambda: |-
          float current = id(realtime_redox).state;
          float diff = current - id(last_redox_trend_value);
          if (diff > 2) {
            id(redox_trend_state) = 1;
          } else if (diff < -2) {
            id(redox_trend_state) = -1;
          } else {
            id(redox_trend_state) = 0;
          }
          id(last_redox_trend_value) = current;
