name: Build

on:
  push:
    branches: [develop, main]
    paths-ignore:
      - 'pcb/**'
      - 'CHANGELOG.md'
      - 'docs/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'pcb/**'
      - 'CHANGELOG.md'
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build firmware (berp)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Get ESPHome version from requirements
        id: get_esphome_version
        run: |
          VERSION=$(grep -i '^esphome==' requirements.txt | awk -F '==' '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build frangipool-berp
        uses: esphome/build-action@6b9d3f593d626a2f0d2c17daebf0a97957d67425  # v8.0.0
        with:
          yaml-file: frangipool-berp.yaml
          version: ${{ steps.get_esphome_version.outputs.version }}
